config/routes.rb
PrincetonPeruPartnership::Application.routes.draw do
  resources :products

  resources :gphotos

  resources :updates

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :events

  get "home/index"

  get "home/crew"

  get "home/events"

  get "pages/home"

  
  root :to => "home#index"
  match '/crew' => "home#crew"
  match '/events' => "events#index"
  match '/donate' => "home#donate"
  match '/news' => "updates#index"
  match '/gallery' => "gphotos#index"
  match '/products' => "products#index"
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
 
  
  #UNCOMMENT BELOW FOR ADMIN USER EMAIL VERIFICATION
  #after_create { |admin| admin.send_reset_password_instructions }
 
  #def password_required?
    #new_record? ? false : super
  #end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/gphoto.rb
class Gphoto < ActiveRecord::Base
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/update.rb
class Update < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

app/controllers/gphotos_controller.rb
class GphotosController < InheritedResources::Base
  def index
    @gphotos = Gphoto.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def crew
  end
  
  def donate
  end

end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  def index
    @products = Product.all
  end
end

app/controllers/updates_controller.rb
class UpdatesController < InheritedResources::Base
  def index
    @updates = Update.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gphotos_helper.rb
module GphotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/events/index.html.erb
<html>
<title>Upcoming Events</title>
<head><link rel = stylesheet href = "style.css" type = "text/css">
</head>
<body>
<p>
<h1 class = "subheader">Upcoming Events</h1>
</p>

<div class ="maintile">
<table cellpadding = "10"class = "eventstable">
<tr>
<th class = "eventstableheader">Event</th>
<th class = "eventstableheader">Date</th>
<th class = "eventstableheader">Place</th>
</tr>


<% @events.each do |event| %>
  <tr>
    <td class = "eventstableelement"><%=event.name%></td>
    <td class = "eventstableelement"><%=event.date%></td>
    <td class = "eventstableelement"><%=event.location%></td>
  </tr>
<% end %>


</table>



</table>


</div>






</body>
</html>

app/views/gphotos/index.html.erb
<html>
<title>Gallery</title>
<head><link rel = stylesheet href = "style.css" type = "text/css">
</head>
<body>
<p>
<h1 class = "subheader">Gallery</h1>
</p>

<div class ="maintile">
<!--table cellpadding = "10"class = "eventstable">
  <!% @gphotos.each_slice(2) do |gphotos| %> 
    <tr>
      
        <!--%gphotos.each do |gphoto|%>
            <!--td class = "standardimage"><!%=image_tag gphoto.avatar.url(:medium) %></td-->
            <!--td class ="standardimage"> <img src="G{gphoto.id}.jpeg" height="300" width="300" /></td-->
          <!--%end%>
    </tr>
    <tr>
        <!%gphotos.each do |g| %>  
          <td class = "gphotocaption"><!%=g.caption%></td>
        <!%end%>
    </tr>
  <!%end%-->
</table>

<table cellpadding = "10"class = "eventstable">
  <tr>
     <td class ="standardimage"> <img src="G1.jpeg" height="300" width="300" /></td>
     <td class ="standardimage"> <img src="G2.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">Summer 2011, Group photo with world-renowned artist: Victor Delfin	</td>
    <td class = "gphotocaption">Summer 2011, Group photo in the Peruvian Andes Mountains		</td>
 
  </tr>
  <tr>
    <td class ="standardimage"> <img src="G3.jpeg" height="300" width="300" /></td>
    <td class ="standardimage"> <img src="G4.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">Stunning views from the Inca Trail, Machu Picchu		</td>
    <td class = "gphotocaption">Summer 2011, Group photo after completing 1-Day, 7 hour trek of Inca Trail			</td>
  </tr>
  <tr>
    <td class ="standardimage"> <img src="G5.jpeg" height="300" width="300" /></td>
    <td class ="standardimage"> <img src="G6.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">Remaining group staying in Peru for community service in Taray		</td>
    <td class = "gphotocaption">Bird's-eye view of Taray 2 YEARS after devastating mudslide disaster	</td>
  </tr>
  <tr>
    <td class ="standardimage"> <img src="G7.jpeg" height="300" width="300" /></td>
    <td class ="standardimage"> <img src="G8.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">Taray school under construction	</td>
    <td class = "gphotocaption">Upper school under construction			</td>
  </tr>
  <tr>
    <td class ="standardimage"> <img src="G9.jpeg" height="300" width="300" /></td>
    <td class ="standardimage"> <img src="G10.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">Menelaos spending time with Tarayian school kids		</td>
    <td class = "gphotocaption">PHS Group at work in constructing bamboo bookshelf from "scratch"		</td>
  </tr>
  <tr>
    <td class ="standardimage"> <img src="G11.jpeg" height="300" width="300" /></td>
    <td class ="standardimage"> <img src="G12.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">The mastermind behind all relief efforts in Taray: Alonso Del Rio		</td>
    <td class = "gphotocaption">PHS Group in front of finished products-Bamboo Bookshelves			</td>
  </tr>
  
  
    <tr>
    <td class ="standardimage"> <img src="G13.jpeg" height="300" width="300" /></td>
    <td class ="standardimage"> <img src="G14.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">PHS Group assembling environmentally friendly "Solar Ovens"			</td>
    <td class = "gphotocaption">On the ground devastation 2 YEARS after mudslide disaster			</td>
  </tr>
  <tr>
    <td class ="standardimage"> <img src="G15.jpeg" height="300" width="300" /></td>
    <td class ="standardimage"> <img src="G16.jpeg" height="300" width="300" /></td>
  </tr>
  <tr>
    <td class = "gphotocaption">What is left of an adobe-brick two-story household 2 YEARS after the mudslide			</td>
    <td class = "gphotocaption">Several household structures completely destroyed by the fatal mudslide				</td>
  </tr>
</table>

</div>

</body>
</html>

app/views/gphotos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_gphoto_path(@gphoto) %> |
<%= link_to 'Back', gphotos_path %>

app/views/home/crew.html.erb
<html>
<title>Meet the Creators</title>
<head><link rel = stylesheet href = "style.css" type = "text/css">
</head>
<body>

<p>
<h1 class = "subheader"> The Crew</h1>
</p>


<div class = "maintile">
  <table border="0" cellpadding ="10" cellspacing ="30">
    <tr>
      <td>
        <div class = "peoplephoto">
          <%= image_tag "Mene Final.jpg", :size=>"150x150", :alt=>"Menelaos Mazarakis"%>
        </div>
      </td>
      <td>
	<div class = "description">
		<p class = "describeperson">Menelaos Mazarakis is currently a sophomore at Princeton Highschool. He is the President and founder of the Princeton Peru Partnership. Among his passions are learning new languages (proficient in 4 languages: Spanish, Greek, English, and French), traveling the world, and studying world cultures. He is also an avid squash player, intense ping-pong'er, and aggressive debater on philosophical issues. After being born and living in New York for a month, Mexico for 5 years, Miami for 1 year, and Boston for another year, he finally settled down in Princeton in 2003. His experiences in Peru inspired him to lead the Princeton Peru Partnership at Princeton Highschool in hopes of aiding the devastated people of Taray. A strong patriot of his native land, Greece, where he spends his summers, Menelaos is a firm believer that: "Without Greek achievement, the world would be much different." -Anonymous </p>
	</div>
      </td>
    </tr>
    
    <tr>
      <td>
        <div class = "peoplephoto">
          <%= image_tag "Hayden Final.jpg", :size=>"150x150", :alt=>"Hayden"%>
        </div>
      </td>
      <td>
        <div class = "description">
          <p class = "describeperson">
          Martha Hayden is the Spanish teacher at Princeton High School. She went to Loyola University undergraduate and Georgetown University as a graduate. She runs her own non-for-profit called Creando Lazos, "Creating Ties." She organizes many philanthropic efforts in Peru involving sustainable energy, healthcare, and microcredit. She lives in Central New Jersey. 
          <p class = "describeperson">Every year, she organizes a trip for a group of her students to visit her home country of Peru. During these trips, she exposes them to the rich culture of her homeland.</p>
          <p class="describeperson">With her hard work and motivated attitude towards teaching her students, she inspired her students to pursue philanthropic efforts in the Peruvian area.</p>
          </p>
        </div>	
      </td>
    </tr>

    <tr>
      <td>
        <div class = "peoplephoto">
          <%= image_tag "Dan Final.jpg", :alt=>"Daniel Black", :size=>"150x150" %>
        </div>
      </td>
      <td>
        <div class = "description">
          <p class = "describeperson">
          Daniel in currently resides in Central New Jersey but spent his early childhood in Europe and the Caribbean. He and several of his Princeton Peru Partnership co-volunteers go to Princeton High School. He attended the Peru trip in summer of 2010 In his spare time, he enjoys studying Andean race relations and emulating Frank Gehry’s unique style of architecture. Between firefighter emergency calls, he works on marketing for Orchive.
          </p>
        </div>
      </td>
    </tr>
    
    <tr>
      <td> 
        <div class = "peoplephoto">
          <%= image_tag "Becca Final.jpg", :alt=>"Rebecca Freda", :size=>"150x150" %>
        </div>
      </td>
      <td>
        <div class = "description">
          <p class = "describeperson">
          Rebecca Freda is a junior at Princeton High School. She is one of the original leaders of Princeton Peru Partnership who went on the 2011 Peru trip. She is now the Chief Culinary Officer of the Princeton Peru Partnership. Among other things, she is co-leader of Knitting For Needs, a club at Princeton High School. She also loves field hockey, plays lacrosse, and is currently working on her Girl Scout Gold Award. In her spare time, Rebecca likes to make ice cream and bake other goods.
          </p>
        </div>
      </td>
    </tr>  

    <tr>
      <td>
        <div class = "peoplephoto">
          <%= image_tag "Liana Final.jpg", :alt=>"Liana Bloom",:size=>"150x150" %>
        </div>
      </td>
      <td>
        <div class = "description">
          <p class = "describeperson">
          Liana Bloom is a sophomore at Princeton High School. She is the Chief Operating Officer of the Princeton Peru Partnership. She attended the Peru trip during the summer of 2011. She enjoys long walks on the beach, playing softball, communicating with others in Spanish, and helping out the community. Liana also is an avid tennis player on the Princeton High School team. She is part of a leader-student exchange program in which students from all across the US are exchanged with students from Israel.
          </p>
        </div>
      </td>
    </tr>
    
    <tr>
      <td>
        <div class = "peoplephoto">
           <%= image_tag "Neil Final.jpg", :size=>"150x150", :alt=>"Neil Limaye"%>
        </div>
      </td>  
      <td>
        <div class = "description">
        <p class = "describeperson">
        Neil Limaye is a freshman at Princeton High School and Chief Technology Officer of the Princeton Peru Partnership. He is close friends with Menelaos and was willingly absorbed into the charity. Neil is currently head of 1 not-for-profit and 1 for-profit company. His hobbies include gaming, programming, playing tabla, Model UN, art, architecture, physics, chemistry, novel studies, and movie analyses. Follow him on Twitter at <a class = "twitterlink" href = "http://www.twitter.com/theclassicneil">@theclassicneil</a>
        </p>
        </div>
      </td>
    </tr>
    
  </table>









</p>
</div>
</div>
</div>

</body>
</html>

app/views/home/donate.html.erb
<html>
<title>Upcoming Events</title>
<head><link rel = stylesheet href = "style.css" type = "text/css">
</head>
<body>
<p>
<h1 class = "subheader">Donate</h1>
</p>

<div class ="maintile">
  <h1 class ="donatetext">
    This feature is not available at this time
  </h1>
  
    <!--form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="S5ASK448YL278">
    <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
    <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </form-->
</div>
</table>


</div>






</body>
</html>

app/views/home/index.html.erb
<html>
<title>Princeton Peru Partnership</title>
<head>
<link rel = stylesheet href = "style.css" type = "text/css">
</head>







<div class = "primarytilecontainer">
	<div class = "maintile">
	<p class = "aboutus">
	Every Summer, one of Princeton High School's Spanish Teachers, Martha Hayden takes a few of her students on a journey that none of them will ever forget, touring her country that is full of culture and heritage...Peru. A few of us chose to stay in a small, rural village - Taray. Merely a year ago, this town faced the unthinkable, being destroyed by a deadly mudslide, leaving hundreds dead. We spent nine days helping re-build the elementary school, which had been totally devastated, forging relationships with the local kids, and finally learning about what we as a people can do for the environment. 

Energized and eager to share our stories to our families, our Peru group felt compelled to organize ourselves and create an action plan within Princeton Highschool to make this goal of giving Winaypaq a chance to look at the future with renewed optimism. The "Princeton Peru Partnership" will meet every Monday at break to coordinate this action plan. Through the course of this year, we want to: 

<ul>
<li>Raise awareness about this cause and energize Princeton High School and the community around it</li>
<li>Brainstorm fundraising ideas and conduct several fundraising events that include: Silent auctions, Bake Sales, A silent auction, Car washes, and local themed fundraising dinners, including Peruvian local specialties (The club will prioritize fundraising ideas and develop the execution plans for each event)</li>
<li>Establish partnerships with other schools such as Princeton Charter, Peddie, and other local organizations.</li>
<li>Organize a trip to Peru in early spring to deliver raised funds.</li>
</ul>


<p style="text-align: center;">If you feel to work for this noble cause, we invite you to help us!</p>

	</p>
	</div>
	</div>

</html>

app/views/layouts/_header.html.erb
<div class = "headerimg">
  <%= image_tag "logo.jpeg", :size => "225x225", :alt => "PrincetonPeruPartnership" %>
  <!-- BANNER GOES HERE-->
</div>

    <h1 class = "superheader"> Princeton Peru Partnership</h1>

app/views/layouts/_navbar.html.erb
<div class = "navbar">
<ul class = "navbarlist">
<li><a class = "navbarlink" href = "/">Home Page</a></li>
<li><a class = "navbarlink" href = "/news">News</a></li>
<li><a class = "navbarlink" href = "/crew">The Crew</a></li>
<li><a class = "navbarlink" href = "/events">Upcoming Events</a></li>
<li><a class = "navbarlink" href = "/gallery">Gallery</a></li>
<li><a class = "navbarlink" href = "/products">Silent Auction</a></li>
<li><a class = "navbarlink" href = "/donate">Donate</a></li>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrincetonPeruPartnership</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<html>
<title>Silent Auction Items</title>
<head><link rel = stylesheet href = "style.css" type = "text/css">
</head>
<body>
<p>
<h1 class = "subheader">Silent Auction Items</h1>
</p>

<div class ="maintile">
<table cellpadding = "10"class = "eventstable">
  <% @products.each_slice(2) do |products| %> 
      <tr>
        <%products.each do |p| %>  
          <td class = "productname"><%=p.name%></td>
        <%end%>
    </tr>    
    <tr>
        <%products.each do |product|%>
            <td class = "standardimage"><%=image_tag product.avatar.url(:medium) %></td>
          <%end%>
    </tr>  
    <tr>
        <%products.each do |p| %>  
          <td class = "productprice"><%=p.price%></td>
        <%end%>
    </tr>
  <%end%>


</table>
</div>

</body>
</html>



<!--% @products.each do |product| %>
  <tr>
    <td><!%= product.name %></td>
    <td><!%= product.price %></td>
    <td><!%= link_to 'Show', product %></td>
    <td><!%= link_to 'Edit', edit_product_path(product) %></td>
    <td><!%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<!% end %>
</table>

<br />

<!%= link_to 'New Product', new_product_path %-->

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/updates/_display.html.erb
<!--div id =""-->
  <tr>
    <tr>
      <td class = "updatetitle"><%=update.title%></td>
    </tr>
    <tr>
      <p>
       <td class = "updatecontent"><%=update.content%></td>
      </p>
    </tr>
    <tr>
      <td class ="updatedate"><%=update.date %></td>
    </tr>

   
  </tr>

app/views/updates/index.html.erb
<html>
<title>Upcoming Events</title>
<head><link rel = stylesheet href = "style.css" type = "text/css">
</head>
<body>
<p>
<h1 class = "subheader">News</h1>
</div></p>

<div class ="maintile">
<table cellpadding = "10"class = "eventstable">

<% @updates.each do |update| %>
  <%= render 'display', :update => update %>
<% end %>



</table>



</div>






</body>
</html>